name: vim-golf

default-extensions:
  - ApplicativeDo
  - LambdaCase
  - RecursiveDo
  - ScopedTypeVariables

executables:
  vim-golf:
    main: Main.hs
    ghc-options: -freverse-errors -threaded -Wall
    dependencies:
      - base                       < 5
      - reactive-banana >= 1.2  && < 1.3
      - vty                        < 5.18
